import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import { CursorGlow } from '@/components/cursor-glow'
import './globals.css'

// NOTE: next/font/google fetches font files from fonts.googleapis.com at build time.
// This is optimal for performance (self-hosting behavior on Vercel), but it will
// fail builds in network-restricted environments (e.g. offline CI runners, sandboxed builds).
// If your build fails here without network access, you should switch to locally hosted
// font files (@font-face in globals.css) as an alternative.
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
  fallback: ['-apple-system', 'Segoe UI', 'sans-serif'],
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
  fallback: ['-apple-system', 'Segoe UI', 'sans-serif'],
})

export const metadata: Metadata = {
  title: '6th Civilians | Deep Tech, Software, AI & IoT Solutions',
  description:
    '6th Civilians is a deep-tech studio engineering end-to-end solutions spanning custom software development, mobile apps, AI & machine learning, cloud architecture, IoT, and EV technology.',
  generator: 'Next.js',
  keywords: [
    '6th Civilians',
    'Deep Tech Studio',
    'Quantum-inspired Research',
    'IT Consulting',
    'software engineering',
    'software development',
    'custom software development',
    'custom software',
    'software services',
    'software technology',
    'bespoke software',
    'web development',
    'web development company',
    'web development services',
    'web development agency',
    'custom web development',
    'ecommerce web development',
    'web application development',
    'web app development',
    'mobile app development',
    'app development',
    'mobile app development company',
    'mobile app development services',
    'ios app development company',
    'android app development company',
    'custom app development',
    'custom mobile app development services',
    'healthcare app development',
    'ai iot',
    'ai software development',
    'iot software development',
    'iot and ai',
    'machine learning software',
    'ai engineer',
    'iot',
    'iot devices',
    'industrial iot',
    'iot solutions',
    'iot network',
    'iot sensors',
    'cloud computing',
    'cloud computing services',
    'cloud storage',
    'seo',
    'seo services',
    'seo agency',
    'local seo',
    'seo company',
    'seo optimization',
    'seo marketing',
    'blockchain',
    'blockchain technology',
    'blockchain services',
    'blockchain platform',
    'ev technology solutions',
    'electric vehicle software systems',
    'ev charging software development',
    'ev firmware development',
    'iot product development',
    'iot embedded systems',
    'connected device development',
    'ai integration for startups',
    'startup mvp build',
    'mvp development',
    'minimum viable product development',
    'tech staff augmentation',
    'software team augmentation',
    'cloud architecture for startups',
    'machine learning implementation',
    'power bi dashboard',
    'data analysis',
    'managed it services',
    'business it services',
    'outsourced it services',
    'it services company',
    'crm system',
    'agence web',
    'internet agentur',
    'web design',
    'software',
    'tournament software',
    'software engineer',
    'sonata software share price',
    'fusion software inst',
    'software engineering',
    'sonata software share',
    'what is software',
    'software engineer salary',
    'crm software',
    'ncc integrated software',
    'video editing software',
    'video conferencing software',
    'photo editing software',
    'fcs software share price',
    'software testing strategies',
    'newgen software share price',
    'application software',
    'accounting software',
    'software developer',
    'zoho crm',
    'crm',
    'zoho crm login',
    'phyzii crm',
    'crm full form',
    'crm login',
    'nyse: crm',
    'crm share price',
    'phyzii crm login',
    'crm stock',
    'crm meaning',
    'what is crm',
    'crm hdfc life',
    'crm tools',
    'kotak crm',
    'voltas crm',
    'recruit crm',
    'dealer crm',
    'sales crm',
    'what is software engineering',
    'spiral model in software engineering',
    'waterfall model in software engineering',
    'software engineering course',
    'cocomo model in software engineering',
    'sdlc in software engineering',
    'agile model in software engineering',
    'rad model in software engineering',
    'srs in software engineering',
    'dfd in software engineering',
    'v model in software engineering',
    'testing in software engineering',
    'data flow diagram in software engineering',
    'functional and non functional requirements in software engineering',
    'software engineering salary',
    'cmmi in software engineering',
    'class diagram in software engineering',
    'risk management in software engineering',
    'use case diagram in software engineering',
    'digital marketing',
    'digital marketing course',
    'what is digital marketing',
    'digital marketing agency',
    'digital marketing services',
    'digital marketing meaning',
    'digital marketing courses',
    'digital marketing company',
    'digital marketing jobs',
    'fundamentals of digital marketing',
    'digital marketing salary',
    'digital marketing images',
    'digital marketing course fees',
    'free online digital marketing courses with certificates by google',
    'best digital marketing agency',
    'digital marketing kya hai',
    'digital marketing logo',
    'types of digital marketing',
    'digital marketing course online',
    'digital marketing tools',
    'public relation',
    'what is public relation',
    'public relation officer',
    'public relation meaning',
    'public relation officer qualification',
    'public relation officer vacancy',
    'public relation agency',
    'public relation officer meaning',
    'public relation executive',
    'what do you mean by public relation',
    'public relation leaders',
    'district public relation officer',
    'national public relation day',
    'public relation officer government jobs',
    'public relation manager',
    'public relation jobs',
    'public relation officer in hindi',
    'public relation nursing home',
    'public relation officer salary',
    'what is public relation officer',
    'ev technology',
    'ev technology courses',
    'senso ev technology',
    'ya ev technology pvt. ltd. jaipur',
    'senso ev technology inc',
    'ev technology course',
    'mtech in ev technology',
    'b tech in ev technology',
    'diploma in ev technology',
    'ya ev technology private limited',
    'm tech in ev technology',
    'ev technology training',
    'new ev technology',
    'academy of ev technology',
    'what is ev technology',
    'ev technology podcasts',
    'oleant ev technology',
    'future ev technology',
    'ev technology services',
    'pg program in ev technology',
    'ev tech',
    'best 7-seater electric suv with advanced ev tech',
    'advanced ev tech in 7 seater electric suvs',
    'which 7-seat electric suv has the best ev tech',
    'breakthrough ev tech',
    'ev tech expo',
    'ev tech is more sustainable',
    'emerging ev tech',
    'ev tech jobs',
    'best 7-seat electric suv ev tech',
    'ev tech news',
    'ev tech stack blueprint',
    'best ev tech in 7-seat electric suvs 2025',
    'mercury ev tech share price',
    'porsche cayenne ev tech innovations',
    'ev tech expo europe 2026',
    'china design how chinese ev tech',
    '7-seat electric suv with best ev tech 2025',
    'ev tech el salvador',
    'china inside how ev tech is',
    'api development',
    'api development services',
    'test wordpress site for api development',
    'custom api development',
    'api development company',
    'api development and integration services',
    'api development tools',
    'custom api development company',
    'custom api development services',
    'api development service',
    'api development and integration',
    'custom api development company in usa',
    'api development companies',
    'hire api development specialists',
    'rest api development services',
    'what is api development',
    'web api development services',
    'python api development',
    'rest api development company',
    'api development collaboration',
    'what is an api',
    'api',
    'api meaning',
    'best api con pastel near me',
    'what is an api key',
    'claude api',
    'gemini api key',
    'fabric api',
    'rest api',
    'openai api key',
    'ldoceonline api',
    'google gemini api key',
    'what is api',
    'anthropic api',
    'google maps api',
    'deepseek api',
    'openai api pricing',
    'what does api stand for',
    'tradingview api',
    'gemini api',
    'ui/ux design',
    'ui/ux',
    'ui/ux designer',
    'ui/ux designer salary',
    'latest ui/ux usability principles 2026 february',
    'what is a ui/ux designer',
    'ui/ux design services',
    'ui/ux designer jobs',
    'what is ui/ux',
    'ui/ux design agency',
    'ui/ux design firm',
    'ui/ux design for defi platforms',
    'ui/ux meaning',
    'ui/ux app development agency',
    'what is ui/ux design',
    'ui/ux design course',
    'ui/ux news',
    'ui/ux designer job description',
    'ui/ux design services company',
    'ui/ux design trends',
    'ui/ux design course free with certificate',
    'ui/ux design course fees',
    'ui/ux design examples',
    'ui/ux design course free',
    'ui /ux design',
    'ui/ux design company',
    'ui/ux design courses',
    'ui /ux design course',
    'ui/ux design agencies',
    'best ui/ux design companies in bangalore',
    'what is ui/ux design course',
    'ui/ux design course syllabus',
    'ui/ux design meaning',
    'ui/ux design course online',
    'ui / ux design',
    'business application',
    'sap business application studio',
    'business application development',
    'business application studio',
    'business application software',
    'business application of e commerce',
    'business application modernization',
    'e business application',
    'what is business application',
    'business application studio sap',
    'business application examples',
    'office 365 dynamics business application',
    'business application development services',
    'advanced business application programming',
    'business application support',
    'custom business application development',
    'business application consulting services',
    'business application letter',
    'business application services',
    'business application of information system',
    'machine learning',
    'what is machine learning',
    'machine learning algorithms',
    'machine learning models',
    'machine learning course',
    'linear regression in machine learning',
    'svm in machine learning',
    'clustering in machine learning',
    'types of machine learning',
    'machine learning projects',
    'artificial intelligence and machine learning',
    'decision tree in machine learning',
    'machine learning definition',
    'knn algorithm in machine learning',
    'machine learning interview questions',
    'pca in machine learning',
    'regression in machine learning',
    'logistic regression machine learning',
    'linear regression machine learning',
    'confusion matrix in machine learning',
    'chatbot',
    'ai chatbot',
    'what is a chatbot',
    'gemini ai chatbot',
    'chatbot ai',
    'uncensored ai chatbot',
    'lg chatbot',
    'what is chatbot',
    'chatbot meaning',
    'best ai chatbot',
    'free ai chatbot',
    'chatbot gpt',
    'grok ai chatbot',
    'whatsapp chatbot',
    'ai chatbot free',
    'eliza chatbot',
    'chatgpt chatbot',
    'chatbot icon',
    'meta ai chatbot',
    'chatbot ui'
  ],
  authors: [{ name: '6th Civilians' }],
  creator: '6th Civilians',
  publisher: '6th Civilians',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://6thcivilians.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: '6th Civilians | Deep Tech, Software, AI & IoT Solutions',
    description:
      'A deep-tech studio delivering software, cloud, AI, IoT, and quantum-inspired solutions from first principle to production.',
    url: 'https://6thcivilians.com',
    siteName: '6th Civilians',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: '6th Civilians | Deep Tech & Software Engineering',
    description: 'A deep-tech studio delivering software, cloud, AI, IoT, and quantum-inspired solutions end to end.',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export const viewport: Viewport = {
  colorScheme: 'dark',
  themeColor: '#0A0C10',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <body className="bg-background text-foreground antialiased">
        <CursorGlow />
        {children}
        {process.env.NODE_ENV === 'production' && <Analytics />}
      </body>
    </html>
  )
}
